# Generated by Django 3.2 on 2022-11-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Расскажите о себе', max_length=500, verbose_name='Об авторе')),
                ('location', models.CharField(blank=True, help_text='Где Вы живете?', max_length=30, verbose_name='Город')),
                ('birth_date', models.DateField(blank=True, help_text='Укажите дату рождения', null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, help_text='Приложите свое фото', upload_to='profile/', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
