# Generated by Django 3.2 on 2022-11-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221128_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/avatar.jpg', help_text='Приложите свое фото', upload_to='profile/', verbose_name='Фото'),
        ),
    ]
