# Generated by Django 3.2 on 2022-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Приложите свое фото', upload_to='profile/', verbose_name='Фото'),
        ),
    ]
